[package]
name = "starknet-validator-attestation"
version = "0.1.2"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.88"
axum = "0.8.1"
clap = { version = "4.5.34", features = ["derive", "env"] }
futures-util = "0.3.31"
metrics = "0.24.1"
metrics-exporter-prometheus = "0.16.2"
reqwest = { version = "0.12.15", default-features = false, features = [
    "json",
    "rustls-tls-native-roots",
] }
reqwest-websocket = { version = "0.4.4", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.140"
starknet = "0.14.0"
starknet-crypto = "0.7.4"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
url = "2.5.4"

[dev-dependencies]
assert_matches = "1.5.0"
